import type {Metadata} from "next";
import "./globals.css";
import React from "react";
import Navbar from "@/components/themes/Navbar";
import Providers from "@/app/Providers";
import {ToastContainer} from "react-toastify";
import 'react-toastify/dist/ReactToastify.css'

export const metadata: Metadata = {
    title: "Somting Coin",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <Providers>
          <html lang="en">
          <body className={"w-full  mx-auto   flex justify-center"}>
          <div style={{height: "calc(100vh)"}} className={"w-full bg-gradient-main  overflow-auto   relative"}>
              <main className={"sm:w-[480px]   p-6 overflow-auto pb-24 mx-auto  text-white"}>
                  <div className="absolute inset-0 h-1/2 bg-gradient-overlay z-0"></div>

                  {children}
                  <Navbar/>
                  <ToastContainer/>
              </main>


          </div>
          </body>
          </html>
      </Providers>
  );
}
